apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-app-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: http-echo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: http-echo
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
        - name: {{ include "devops-app-chart.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-text={{ include "devops-app-chart.fullname" . }}!"
          ports:
            - name: http
              containerPort: 5678
