apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-app-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: http-echo
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app: http-echo
