replicaCount: 2
image:
  repository: hashicorp/http-echo
  tag: 0.2.3
  pullPolicy: IfNotPresent

namespace: app1

service:
  type: ClusterIP
  port: 5678

ingress:
  enabled: true
  annotations: {}
  path: /
  pathType: Prefix
  hosts:
    - app1.kind.cluster