apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 3
  revisionHistoryLimit: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
  strategy:
    canary:
      canaryService: rollouts-demo-canary
      stableService: rollouts-demo-stable
      steps:
      - setWeight: 30
        pause: {}
      - setWeight: 60
        pause: {}
      - setWeight: 100
      trafficRouting:
        nginx:
          stableIngress: rollouts-demo-stable
          trafficSplit:
          - percent: 70
            name: rollouts-demo-stable
          - percent: 30
            name: rollouts-demo-canary
