replicaCount: 2
image:
  repository: hashicorp/http-echo
  tag: 0.2.3
  pullPolicy: IfNotPresent

namespace: app2

service:
  type: LoadBalancer
  port: 5678

ingress:
  enabled: true
  annotations: {}
  path: /
  pathType: Prefix
  hosts:
    - app2.kind.cluster