apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-app
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: http://chartmuseum.chartmuseum.svc.cluster.local
    chart: devops-app-chart
    targetRevision: 0.5.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
